MoMofy to public
EBI-Metagenomics/momofy pull request #5
Opened 2023-03-21 13:07 UTC by Ales-ibt

Unit test still pending. Thank you for checking the code in the meantime :D

2023-03-23 12:33 UTC, mberacochea requested changes
Great stuff!! I've added some comments for you to review.

2023-03-23 12:33 UTC, mberacochea commented on README.md
> +This workflow was implemented to be run through [Nextflow](https://www.nextflow.io/) and use [Docker](https://www.docker.com/) to build the image of ICEfinder.
```suggestion
This workflow is built using [Nextflow](https://www.nextflow.io/).  It uses Docker/Singularity containers making installation trivial and results highly reproducible.
There is one manual step required to build the Docker image for [ICEfinder](https://bioinfo-mml.sjtu.edu.cn/ICEfinder/index.php), we can't distribute that software due to license issues. 
```

2023-03-23 12:33 UTC, mberacochea commented on README.md
> +$ nextflow run format_mobileOG.nf
The download and db processing step is alright. But, we could improve this later and have the pipeline download the db if it's missing when running the first time

2023-03-23 12:33 UTC, mberacochea commented on README.md
> +One input file is mandatory in a folder called `raw_data`:
Why do we need to have this folder named like that?

2023-03-23 12:33 UTC, mberacochea commented on README.md
> +$ nextflow run /PATH/momofy/momofy.nf --assembly raw_data/contigs.fasta -with-docker my_icefinder
```suggestion
$ nextflow run /PATH/momofy/momofy.nf --assembly raw_data/contigs.fasta my_icefinder 
```
The `-with-docker` can be left out IMO. I would make the default config to use docker

2023-03-23 12:33 UTC, mberacochea commented on README.md
> +A GFF validation process is used to detect formatting errors in the final GFF3 output. This process can be skipped adding `--validator false`.
```suggestion
A GFF validation process is used to detect formatting errors in the final GFF3 output. This process can be skipped adding `--gff-validation false`.
```

2023-03-23 12:33 UTC, mberacochea commented on README.md
> +The main outputs of MoMofy are in the `MoMofy_results`. There you will find the following files:
The output directory should be a parameter `--outdir`

2023-03-23 12:33 UTC, mberacochea commented on README.md
> +The main outputs of MoMofy are in the `MoMofy_results`. There you will find the following files:
Some users may want to store the input and output files in different places. It is also easier to use when you can specify the folder you want the results to be

2023-03-23 12:33 UTC, mberacochea commented on README.md
> +│   │   └── contig.prokka_1.gbk
We may want to retain the original fasta name instead of renaming it to "contigs".

2023-03-23 12:33 UTC, mberacochea commented on bin/assembly_filter_rename.py
> +warnings.filterwarnings("ignore", category=DeprecationWarning)
Why are we suppressing those 2 warnings?

2023-03-23 12:33 UTC, mberacochea commented on bin/assembly_filter_rename.py
> +with open(output_1kb, 'w') as to_1kb, open(output_5kb, 'w') as to_5kb, open(output_map, 'w') as to_map:
Please add the `__name__ == "__main__" ` idiom.
```python
rename():
    # your code

if __name__ == "__main__":
     rename()
```

The reason -> https://realpython.com/if-name-main-python/

2023-03-23 12:33 UTC, mberacochea commented on bin/assembly_filter_rename.py
> +with open(output_1kb, 'w') as to_1kb, open(output_5kb, 'w') as to_5kb, open(output_map, 'w') as to_map:
Also, please run `black` on it (the code formatter).  Have you installed the precommit hooks?

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +            if not line.startswith('#'):
This is just a pedantic comment, but I tend to invert this conditionals to avoid overidenting the code:
```
if line.startswith('#')
    continue
# The logic goes here
```
I find this easier to read

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +if os.path.exists(viri):
Do we want to fail if the file is missing? Otherwise, this goes unnoticed

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +    if os.path.exists(summ_file):
Do we want to fail if the file is missing? Otherwise, this goes unnoticed

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +            Header,Length,phage_score,chromosome_score,plasmid_score,Possible_source=line.rstrip().split(',')
Code styling, we should use a consistent casing for the variables. This has a mixed bag:
`phage_score` which is snake_case and `Header` which is just title cased

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +parser.add_argument('--virify_gff', type=str, help='Virify output in gff format')
None of the args are required.. is that OK?.

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +                        if contig not in contig_phages.keys():
```suggestion
contig_phages.setdefault(contig, []).append(seq_id)
```
The `setdefault` instruction will get the `contig` from the dict, but if missing it will add it and the value will be an empty `[]` (which you can use with `.append` immediatly.

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +        if len(l_line)==9:
Can you add a comment to explain this `==9` conditional?

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +                if seqid in plasmids.keys():
```suggestion
                if seqid in plasmids:
```

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +            if composite_key in protcoord_protid.keys():
```suggestion
            if composite_key in protcoord_protid:
```

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +                new_attrib=attrib+';'+viphog_annot+';'+viphog_taxonomy
```suggestion
                new_attrib = ";".join([attrib, viphog_annot, viphog_taxonomy])
```
I think this improves the readability

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +    to_over.write('#contig\tintegron_ID\tphage_ID\tintegron_cov\tphage_cov\tintegron_len\tphage_len\n')
```suggestion
to_over.write(
    "\t".join(
        ["#contig", "integron_ID", "phage_ID", "integron_cov", "phage_cov", "integron_len", "phage_len"]
    )
    + "\n"
)
```
I think this improves the readability

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +    for integron in momo_pred.keys():
```suggestion
    for integron in momo_pred:
```

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +        m_contig=momo_pred[integron][0]
I think unpacking this makes it easier to read

2023-03-23 12:33 UTC, mberacochea commented on bin/cross_momo_viri.py
> +        for phage in phages_metadata.keys():
```suggestion
        for phage in phages_metadata:
```

2023-03-23 12:33 UTC, mberacochea commented on bin/gbk_splitter.pl
Perl? We should migrate this one to python at some point

2023-03-23 12:33 UTC, mberacochea commented on bin/mge_integrator.py
> +if os.stat(map_file).st_size > 0:
Do we need this check? If the file is empty then the iteration over the lines won't run, or am I mistaken?

2023-03-23 12:33 UTC, mberacochea commented on bin/mge_integrator.py
Some of my previuos comments about a more pythonic code apply to this script too:
- __name__ == "__main__"
- not using .keys for dicts
- the warning being ignored
- running black to format the code
- variable name convention (snake_case)

2023-03-23 12:33 UTC, mberacochea commented on bin/mge_integrator.py
> +        next(input_table)
`next` called twice?

2023-03-23 12:33 UTC, mberacochea commented on bin/mge_integrator.py
2 more thing, please add methods split the logic in different units. For example `parse_palidis`, so the code is easier to read and to test.

Can you please add a couple of unit tests for this code? You can use this one as an example -> https://github.com/EBI-Metagenomics/genomes-pipeline/blob/feature/nf-migration/tests/scripts/test_process_crispr_results.py

2023-03-23 12:33 UTC, mberacochea commented on bin/mge_integrator.py
> +    element_len=int(mge_data[element][2][1])-int(mge_data[element][2][0])
Not now, but at some point it would be a good idea to refactor this. There are too many dicts to store the state, this leads to code that is harder to read (i.e. you need to remember what is stored in [2][0] of the dict).

[namedtuple](https://docs.python.org/3/library/collections.html#collections.namedtuple) are a good alternative, as you can give the properties names (data.start, data.end... and such)

2023-03-23 12:33 UTC, mberacochea commented on bin/mgnify_v5annot_fixer.py
Some of my previuos comments about a more pythonic code apply to this script too:

    name == "main"
    not using .keys for dicts
    the warning being ignored
    running black to format the code
    variable name convention (snake_case)

2023-03-23 12:33 UTC, mberacochea commented on modules/gbk_splitter.nf
> +    if (gbk_file.size() > 0)
Why do we need to check if the input file has content?

I feel this was put in place to run the pipeline with some files and other missing, a better alternative is the `stub` directive -> https://www.nextflow.io/docs/latest/process.html#stub

2023-03-23 12:33 UTC, mberacochea commented on modules/gbk_splitter.nf
> +    resDir = file("$launchDir/icefinder_results/result")
The `publishDir` directive will create the directories it needs

2023-03-23 12:33 UTC, mberacochea commented on modules/gbk_splitter.nf
> +    tmpDir = file("$launchDir/icefinder_results/tmp")
What is this folder used for? If it's used by the tool it should be created in the `script` section

2023-03-23 12:33 UTC, mberacochea commented on modules/integrator.nf
> +	path 'test.out'
do we need this output file?

2023-03-23 12:33 UTC, mberacochea commented on modules/gbk_splitter.nf
> +    publishDir "$launchDir/icefinder_results/gbk", pattern: '*.gbk', mode: 'copy'
```suggestion
    publishDir "${params.outdir}/icefinder_results/gbk", pattern: '*.gbk', mode: 'copy'
```

2023-03-23 12:33 UTC, mberacochea commented on modules/run_diamond.nf
> +        path proteins_file, name: 'proteins.faa'
I think we shouldn't rename the files, I think most users would like to have the output files being named after the original file

2023-03-23 12:33 UTC, mberacochea commented on modules/run_diamond.nf
> +    stageInMode = 'copy'
Do we need to copy the files? Is diamond not happy with the symlink? It saves storage, and copy should be used if the tool doesn't like links.

2023-03-23 12:33 UTC, mberacochea commented on modules/run_icefinder.nf
> +    containerOptions="--bind $PWD/icefinder_results/input.list:/install/ICEfinder_linux/input.list --bind $PWD/icefinder_results/gbk/:/install/ICEfinder_linux/gbk/ --bind $PWD/icefinder_results/tmp/:
The `--bind` parameter is for singularity, for docker is called `--volume`.
```suggestion
    containerOptions "${ workflow.containerEngine == 'singularity' ?
        '--bind $PWD/icefinder_results/input.list:/install/ICEfinder_linux/input.list --bind $PWD/icefinder_results/gbk/:/install/ICEfinder_linux/gbk/ --bind $PWD/icefinder_results/tmp/:/install/ICEfinder_linux/tmp/ --bind $PWD/icefinder_results/result/:/install/ICEfinder_linux/result/ --pwd /install/ICEfinder_linux/' :
        '--volume $PWD/icefinder_results/input.list:/install/ICEfinder_linux/input.list --volume $PWD/icefinder_results/gbk/:/install/ICEfinder_linux/gbk/ --volume $PWD/icefinder_results/tmp/:/install/ICEfinder_linux/tmp/ --volume $PWD/icefinder_results/result/:/install/ICEfinder_linux/result/ --pwd /install/ICEfinder_linux/' }"
```

2023-03-23 12:33 UTC, mberacochea commented on modules/run_integronfinder.nf
> +    stageInMode = 'copy'
Does it need to be copied over instead of just simlinked?

2023-03-23 12:33 UTC, mberacochea commented on modules/run_integronfinder.nf
> +	if ls -l Results_Integron_Finder_contigs/contig_*.gbk 2>/dev/null | grep -q .
Another way to handle this is to make the output files `optional: true`

2023-03-23 12:33 UTC, mberacochea commented on modules/validator.nf
> +process momo_validator {
This one should be called `gff_validation`

2023-03-23 12:33 UTC, mberacochea commented on momofy.nf
> +include { diamond_mob } from './modules/run_diamond'
The modules should not be prefixed `run_<module>` (`run_prokka` -> `prokka`)

2023-03-23 12:33 UTC, mberacochea commented on momofy.nf
> +        ice_finder(gbk_split.out.gbks, file( "icefinder_results/gbk"), file( "icefinder_results/tmp"), file( "icefinder_results/result"))
Are the `icefinder_results` files a `publishDir`?

2023-03-23 12:33 UTC, mberacochea commented on nextflow.config
> +}
We need to add a `docker` profile here in case someone wants to run it with docker

2023-03-29 10:11 UTC, Ales-ibt commented on README.md
> +$ nextflow run format_mobileOG.nf
Oki, the problem is that I couldn't find the way to download the database using wget or curl, that's why I left the instructions that way. As you recommend, we can solve this later.

2023-03-29 10:14 UTC, Ales-ibt commented on README.md
> +One input file is mandatory in a folder called `raw_data`:
We don't really need it. This is just a recommendation on how to organize the sample directory, but this structure is not mandatory. I'll add a sentence to clarify this.

2023-03-29 10:20 UTC, Ales-ibt commented on README.md
> +The main outputs of MoMofy are in the `MoMofy_results`. There you will find the following files:
Ok, I'll add the option and use MoMofy_results as the default

2023-03-29 11:01 UTC, Ales-ibt commented on bin/cross_momo_viri.py
> +if os.path.exists(viri):
We don't want to fail because it could be OK to don't have viral predictions in the assembly. Moreover, as virify runs independently of momofy, any issue regarding phage predictions is out of scope of this repo.

2023-03-29 11:06 UTC, Ales-ibt commented on bin/cross_momo_viri.py
> +    if os.path.exists(summ_file):
Same case as above, it could be OK to don't have viral predictions at all.

2023-03-29 11:09 UTC, Ales-ibt commented on bin/cross_momo_viri.py
> +            Header,Length,phage_score,chromosome_score,plasmid_score,Possible_source=line.rstrip().split(',')
Ok, I'll remove all upper-case variable names.

2023-03-29 11:12 UTC, Ales-ibt commented on bin/cross_momo_viri.py
> +parser.add_argument('--virify_gff', type=str, help='Virify output in gff format')
You are right, at least momofy_gff should be mandatory

2023-03-29 11:14 UTC, Ales-ibt commented on bin/cross_momo_viri.py
> +        if len(l_line)==9:
Ok

2023-03-29 12:25 UTC, Ales-ibt commented on bin/mge_integrator.py
> +if os.stat(map_file).st_size > 0:
You are right :D

2023-03-29 12:28 UTC, Ales-ibt commented on bin/assembly_filter_rename.py
> +warnings.filterwarnings("ignore", category=DeprecationWarning)
I'll remove it

2023-03-29 12:30 UTC, Ales-ibt commented on bin/mge_integrator.py
> +        next(input_table)
Yes, the input file has two lines of header

2023-03-29 12:33 UTC, Ales-ibt commented on bin/mgnify_v5annot_fixer.py
I'll standardise all python scripts to follow these rules

2023-03-29 12:39 UTC, Ales-ibt commented on modules/gbk_splitter.nf
> +    if (gbk_file.size() > 0)
As it is valid that not all types of MGEs are found in a sample (actually, an assembly could lack mobilome), we generated the empty files to prevent the workflow from failing because of the lack of output and to avoid passing empty channels to the final script. There could be a better solution for this.

2023-03-29 12:43 UTC, Ales-ibt commented on modules/integrator.nf
> +	path 'test.out'
We don't need it, I use it for debugging... I'll remove it

2023-03-29 12:44 UTC, Ales-ibt commented on modules/gbk_splitter.nf
> +    publishDir "$launchDir/icefinder_results/gbk", pattern: '*.gbk', mode: 'copy'
ok

2023-03-29 12:47 UTC, Ales-ibt commented on modules/run_diamond.nf
> +    stageInMode = 'copy'
The only tool that complains about links is ICEfinder. I'll keep links for the rest of the tools

2023-03-29 12:50 UTC, Ales-ibt commented on modules/validator.nf
> +process momo_validator {
OK

2023-03-29 12:51 UTC, Ales-ibt commented on momofy.nf
> +include { diamond_mob } from './modules/run_diamond'
I'll change them accordingly

2023-03-29 12:53 UTC, Ales-ibt commented on momofy.nf
> +        ice_finder(gbk_split.out.gbks, file( "icefinder_results/gbk"), file( "icefinder_results/tmp"), file( "icefinder_results/result"))
Yes, but running ICEfinder is a bit tricky, if I don't declare the directories as inputs, I get an error due to writing permission

2023-03-29 12:56 UTC, Ales-ibt commented on bin/cross_momo_viri.py
> +            if not line.startswith('#'):
Ok, I'll try to avoid negative conditionals

2023-03-29 13:09 UTC, Ales-ibt commented on modules/run_icefinder.nf
> +    containerOptions="--bind $PWD/icefinder_results/input.list:/install/ICEfinder_linux/input.list --bind $PWD/icefinder_results/gbk/:/install/ICEfinder_linux/gbk/ --bind $PWD/icefinder_results/tmp/:
I'd to keep everything running from singularity containers. I'll test getting the singularity image from the docker file using [spython](https://singularityhub.github.io/singularity-cli/).

2023-03-29 13:12 UTC, Ales-ibt commented on bin/assembly_filter_rename.py
> +with open(output_1kb, 'w') as to_1kb, open(output_5kb, 'w') as to_5kb, open(output_map, 'w') as to_map:
Ok

2023-04-06 08:30 UTC, merged